# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Build, Test and Upload to SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn install sonar:sonar -Dsonar.host.url="https://sonarcloud.io" -Dsonar.organization=chesstournamentmanager -Dsonar.projectKey=ChessTournamentManager_user-svc

    - name: Login to DockerHub
      if: success() && github.ref == 'refs/heads/main'
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      if: success() && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        push: true
        tags: judahlit/chess_tournament_manager:user-svc